<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWq93LFh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWq93LFh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWq93LFh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWq93LFh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWq93LFh\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wq93LFh',
    'container.build_id' => 'be06df69',
    'container.build_time' => 1599487294,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWq93LFh');
